### ISSUE TITLE
Bug: select2 puts settings.js and style.css in frontend

### ISSUE THREAD

**Issue by johanneslamers** [madebyshape/select2#2]
Hey

When in DevMode Select2 is outputting settings.js and style.css in my frontend. 
Settings.js also gives me an error ($ is not defined) because the script is before of my jQuery file.

**Comment by madebyshape** [comment]
No problem - Will push a fix for this shortly. Obviously should only include the CSS and JS in the CMS.

**Comment by madebyshape** [comment]
Fixed this now in latest build, sorry for the delay just been majorly busy.

Just update :)
